language: julia
os:
  - linux
  - osx
julia:
  - nightly
notifications:
  email: false
script:
    - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
    - julia -e 'Pkg.clone(pwd())'
    - julia -e 'Pkg.checkout("GeometryTypes");'
    - julia -e 'Pkg.test("Meshes", coverage=true)'

after_success:
  - julia -e 'cd(Pkg.dir("Meshes")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder()); Codecov.submit(process_folder())'
