language: julia
os:
  - linux
  - osx
julia:
  - release
  - nightly
notifications:
  email: false
script:
    - julia -e 'Pkg.init(); Pkg.clone(pwd())'
    - julia -e 'Pkg.add("Lint");'
    - julia -e 'Pkg.test("Meshes", coverage=true)'

after_success:
  - julia -e 'cd(Pkg.dir("Meshes")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
